### ISSUE TITLE
2个群主手滑的小问题反馈，迁移不成功的童鞋看一下

### ISSUE THREAD

**Issue by LaoFang1s** [assimon/dujiaoka-tools#1]
1、编译好的二进制文件，没有打包conf文件进去，要手动放进去。
2、另外教程里说的运行命令打错了 应该是 ./dujiaofa-tools -h   迁移命令：./dujiaoka-tools mvtt

**Comment by LaoFang1s** [comment]
另外 迁移不包括商品图片、支付设置

**Comment by alvincheang** [comment]
小白在此，怎么手动放进去那个conf文件？

**Comment by LaoFang1s** [comment]
> 小白在此，怎么手动放进去那个conf文件？

![image](https://user-images.githubusercontent.com/44582189/127034636-c111de5c-30ca-4f4c-b2d5-37ee390daa66.png)
这里有啊

**Comment by assimon** [comment]
这个工具我才写完，连教程都还没写你们就开始用了，我有什么办法/(ㄒoㄒ)/~~

**Comment by alvincheang** [comment]
> 这个工具我才写完，连教程都还没写你们就开始用了，我有什么办法/(ㄒoㄒ)/~~

哈哈 那我还是等大大写教程好了 :D

**Comment by alvincheang** [comment]
> > 小白在此，怎么手动放进去那个conf文件？
> 
> ![image](https://user-images.githubusercontent.com/44582189/127034636-c111de5c-30ca-4f4c-b2d5-37ee390daa66.png)
> 这里有啊

我知道这里有，不过我的意思是我不知道怎么把这个文件放进去已经编译好的那个.

**Comment by LaoFang1s** [comment]
> > > 小白在此，怎么手动放进去那个conf文件？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/44582189/127034636-c111de5c-30ca-4f4c-b2d5-37ee390daa66.png)
> > 这里有啊
> 
> 我知道这里有，不过我的意思是我不知道怎么把这个文件放进去已经编译好的那个.

额。。
