### ISSUE TITLE
卡密和订单迁移失败

### ISSUE THREAD

**Issue by alvincheang** [assimon/dujiaoka-tools#2]
终于自己搞会了 上传到conf到根目录就可以了 @@ 哈哈 可是遇上以下问题

2021/07/27 03:29:20 D:/Code/go/dujiaoka_migrate/models/new_carmis.go:24 empty slice found
[0.278ms] [rows:0] INSERT INTO `carmis` (`goods_id`,`status`,`carmi`,`created_at`,`updated_at`,`deleted_at`) VALUES 
卡密迁移失败，已终止。 错误：empty slice foundERROR: empty slice found

开始迁移商品分类...
商品分类迁移成功！
开始迁移商品...
商品迁移成功！
开始迁移优惠券...
优惠券迁移成功！
开始迁移卡密...

迁移了卡密就有以上错误。是哪里出了问题吗？商品都成功迁移了，就是卡密和订单无法迁移

**Comment by LaoFang1s** [comment]
你2.0是新安装的么，安装后不要设置任何卡密、商品。直接迁移。我一开始也报错，删除根目录 install.lock 文件，重新进网址对接新的数据库。然后直接迁移。

**Comment by alvincheang** [comment]
嗯的 新安装 什么都没设置 就有上面的错误，那我试试你的方法，谢谢啊

**Comment by alvincheang** [comment]
> 你2.0是新安装的么，安装后不要设置任何卡密、商品。直接迁移。我一开始也报错，删除根目录 install.lock 文件，重新进网址对接新的数据库。然后直接迁移。

install lock只是重新安装对吗？不过的我的情况是我的2.0就是安装了啥都没直接迁移的，就有以上错误。

**Comment by alvincheang** [comment]
应该是因为我的1.8是魔改版 所以迁移出现部分问题 卡密和订单无法迁移。没办法了，还好 商品的可迁移。
